figure(1)
semilogy(black_statistics.snrVector, black_statistics.berMean, '-*', ...
     hann_statistics.snrVector, hann_statistics.berMean, '-o', ...
     kaiser_statistics.snrVector, kaiser_statistics.berMean, '-x', ...
     rect_statistics.snrVector, rect_statistics.berMean, '-s', ...
     ofdm_statistics.snrVector, ofdm_statistics.berMean, '-d')
 if isequal(black_statistics.simulationParamters.Multipath, 'Unitary Channel')
    str = sprintf("fOFDM and OFDM - Multipath: %s - %s - AWGN channel", ...
    black_statistics.simulationParamters.Multipath, black_statistics.simulationParamters.modulation);    
 else
     str = sprintf("fOFDM and OFDM - Multipath: %s %s - %s - AWGN channel", ...
     black_statistics.simulationParamters.Multipath, black_statistics.simulationParamters.typeChannel, black_statistics.simulationParamters.modulation);     
 end
title(str)
xlabel("SNR [dB]")
ylabel("BER")
legend("Blackman", "Hanning", "Kaiser", "Rectangular", "OFDM")
grid on